FROM php:8.1-fpm-alpine

RUN apk update && \
    apk add bash build-base gcc wget git autoconf libmcrypt-dev \
    g++ make openssl-dev \
    php81-openssl \
    php81-pdo_mysql \
    php81-mbstring
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql